apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jstrachan:
          repos:
            godemo62:
              required_status_checks:
                contexts:
                - pr-build
            jx3-demo-kubernetes:
              required_status_checks:
                contexts:
                - promotion-build
            nodey490:
              required_status_checks:
                contexts:
                - pr-build
            nodey491:
              required_status_checks:
                contexts:
                - pr-build
            nodey492:
              required_status_checks:
                contexts:
                - pr-build
      protect-tested-repos: true
    github:
      LinkURL: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      jstrachan/godemo62:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
      jstrachan/jx3-demo-kubernetes:
      - agent: tekton
        branches:
        - master
        name: promotion
        skip_report: true
      jstrachan/nodey490:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
      jstrachan/nodey491:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
      jstrachan/nodey492:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
    presubmits:
      jstrachan/godemo62:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/jx3-demo-kubernetes:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey490:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey491:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey492:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/godemo62: merge
        jstrachan/jx3-demo-kubernetes: merge
        jstrachan/nodey490: merge
        jstrachan/nodey491: merge
        jstrachan/nodey492: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo-kubernetes
        - jstrachan/godemo62
        - jstrachan/nodey490
        - jstrachan/nodey491
        - jstrachan/nodey492
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo-kubernetes
        - jstrachan/godemo62
        - jstrachan/nodey490
        - jstrachan/nodey491
        - jstrachan/nodey492
      target_url: http://deck-jx.34.78.85.241.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
